config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  resources :students
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :addresses
  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1> Courses for all the little Spoiled Brats </h1>

<% @courses.each do |course| %>
  <li><%= link_to course.course_name, course_path(course.id) %></li>
<% end %>

<%= link_to "Spoiled Brat Index", students_path %>

app/views/courses/show.html.erb
<h1><%= @course.course_name %> Roster</h1>

<% @course.students.each do |student| %>
  <li><%= student.first_name %></li>
<% end %>

<%= link_to "Course Index", courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBasic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1> Spoiled Brats </h1>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.first_name, student_path(student.id) %></li>
  <% end %>
</ul>

<%= link_to "Course List", courses_path %>

app/views/students/show.html.erb
<h1><%= @student.first_name %></h1>

<h4> Addresses: </h4>
  <% @student.addresses.each do |address| %>
    <li><%= address.address %></li>
  <% end %>

<h4> Courses: </h4>
  <% @student.courses.each do |course| %>
    <li><%= link_to course.course_name, course_path(course.id) %></li>
  <% end %>

<%= link_to "Spoiled Brat Index", students_path %>